version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      GPT_APIKEY: ${GPT_APIKEY}
      GPT_MODEL_NAME: ${GPT_MODEL_NAME}
      APP_ENV: ${APP_ENV}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

